# Generated by Django 5.1.2 on 2024-11-03 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indumentaria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remera',
            name='talle',
            field=models.CharField(max_length=20),
        ),
    ]
